#!/bin/sh

# motd is generated with empty environment. This ensures that TERM is set, so that colors are displayed properly
#  src: https://unix.stackexchange.com/a/417223/31104
export TERM="${TERM:-xterm-256color}"

# RED=$(tput setaf 1)
# GREEN=$(tput setaf 2)
# YELLOW=$(tput setaf 3)
# BLUE=$(tput setaf 4)
# VIOLET=$(tput setaf 5)
# SOME_COLOR=$(tput setaf 6)
WHITE=$(tput setaf 7)
RESET_STYLE=$(tput sgr0)

echo
echo -n "${WHITE}Raspberry Pi ($(hostname))${RESET_STYLE} " && uname -rvm
uptime
